### PR TITLE
document how to generate examples for buildtest tutorial

### PR DESCRIPTION
**Pull request by shahzebsiddiqui**

### CODE REVIEW

**Review by prathmesh4321 — CHANGES_REQUESTED** [review]
@shahzebsiddiqui  I think it should be source scripts/spack_container/setup.sh https://github.com/buildtesters/buildtest/pull/1289/files#:~:text=source%20scripts/spack_container/setup.py

Also the command is not able to create a virtual env when I run it inside the container. I t gives the following error: 
image

**Comment by shahzebsiddiqui** [comment]
> @shahzebsiddiqui I think it should be source scripts/spack_container/setup.sh https://github.com/buildtesters/buildtest/pull/1289/files#:~:text=source%20scripts/spack_container/setup.py
> 
> Also the command is not able to create a virtual env when I run it inside the container. I t gives the following error: image

good catch i had a typo i changed `setup.py` -> `setup.sh` in my latest commit. 

Also regarding the screenshot it looks like it failed on the `module` command i wonder if you can try `docker run -it -v  $BUILDTEST_ROOT:/home/spack/buildtest ghcr.io/buildtesters/buildtest_spack:latest /bin/bash` and see if that creates an interactive shell. What you should expect is the following

```
(buildtest)  ~/Documents/github/buildtest/ [docs_on_autogenerated_examples] docker run -it -v  $BUILDTEST_ROOT:/home/spack/buildtest ghcr.io/buildtesters/buildtest_spack:latest
==> Regenerating tcl module files
spack@5c7f013efe70:~$ ls -ld /home/spack/buildtest/
drwxr-xr-x 41 root root 1312 Oct 28 19:12 /home/spack/buildtest/
spack@5c7f013efe70:~$ module list
No modules loaded
spack@5c7f013efe70:~$ cd /home/spack/buildtest/
spack@5c7f013efe70:~/buildtest$ source scripts/spack_container/setup.sh 
(buildtest) spack@5c7f013efe70:~/buildtest$ module list

Currently Loaded Modules:
  1) python/3.8.6-gcc-7.5.0

 

(buildtest) spack@5c7f013efe70:~/buildtest$ which python
/home/spack/pyenv/buildtest/bin/python
(buildtest) spack@5c7f013efe70:~/buildtest$ python --version
Python 3.8.6
(buildtest) spack@5c7f013efe70:~/buildtest$ which buildtest
/home/spack/buildtest/bin/buildtest
(buildtest) spack@5c7f013efe70:~/buildtest$ buildtest cg p
/home/spack/buildtest/buildtest/settings/spack_container.yml

```

**Comment by prathmesh4321** [comment]
The examples are getting generated but need to do  "source /etc/profile" as we discussed after the docker run command. 

image

**Comment by shahzebsiddiqui** [comment]
> The examples are getting generated but need to do "source /etc/profile" as we discussed after the docker run command.
> 
> image

thanks for confirming. Ill put a note about `source /etc/profile`

**Pull request merged**
