### PR TITLE
LBNL license

### PR DESCRIPTION
**Pull request by shahzebsiddiqui**
@vsoch  you should have got email from Jean on the latest license. I took a look at applied these changes in the repo.

I was wondering if the license needs to preserve previous history since it started in 2017. I might have some questions ill ping you in slack.

### CODE REVIEW

**Comment by vsoch** [comment]
Good question! I think it would be fine to leave with just 2021, because from 2017 to 2020 it had a different form of the license. If someone downloads a previous version, they will see that previous form. I’ve seen other projects try to include both headers, but I’m not sure that does any good other than take up more space, especially if one of the ranges is expired.

**Comment by shahzebsiddiqui** [comment]
That's a good point, the license hasn't changed it's still MIT just copyright has changed. I have seen some projects have several `LICENSE.*` files for different license i presume that's not the case in this situation. 

In any case, i tried to make change to the relevant sections where license banner should be updated. In the email in copyright section, I was bit confused where to insert paragraph 2 and 3. It don't think this belongs in LICENSE file so not sure where i put this. I can ask them for clarification.

```
buildtest Copyright (c) 2021, The Regents of the University of California,
through Lawrence Berkeley National Laboratory (subject to receipt of
any required approvals from the U.S. Dept. of Energy) and Vanessa 
Sochat. All rights reserved.

If you have questions about your rights to use or distribute this software,
please contact Berkeley Lab's Intellectual Property Office at
IPO@lbl.gov.

NOTICE.  This Software was developed under funding from the U.S. Department
of Energy and the U.S. Government consequently retains certain rights.  As
such, the U.S. Government has been granted for itself and others acting on
its behalf a paid-up, nonexclusive, irrevocable, worldwide license in the
Software to reproduce, distribute copies to the public, prepare derivative 
works, and perform publicly and display publicly, and to permit others to do so.
```

**Comment by vsoch** [comment]
Take a look at the spack repos, they have a separate COPYRIGHT and NOTICE file.

**Comment by shahzebsiddiqui** [comment]
I see now, I was comparing buildtest with timemory project https://github.com/NERSC/timemory which has a MIT license from LBNL i didn't see the notice or copyright file. I will try to get some clarification on whether i need to have separate file to cover paragraph 2 and 3.

**Comment by vsoch** [comment]
Good work @shahzebsiddiqui ! If more contributors come along, you can use a strategy like having an AUTHORS or CONTRIBUTORS file (broken into sections like maintainers, contributors) and then you can ask your institution how they want to go about accepting contributions (e.g., either just a note in a PR, or everything up to making them accept a CLA agreement like opencontainers does).

**Comment by shahzebsiddiqui** [comment]
Thanks for the suggestion. I like this idea of AUTHORS and CONTRIBUTORS when the time comes. Right now it's just too early to do this hoping if more sites start using buildtest than we can get  more **users** --> **casual contributors** --> **maintainers**. 

This process takes time and dedication

**Pull request merged**
