### PR TITLE
add new command 'buildtest info'

### PR DESCRIPTION
**Pull request by shahzebsiddiqui**
@Xiangs18 take a look at this command and let me know your thoughts if this looks useful. If there is any additional details that should be captured.

This is what the output looks like 

```
(buildtest)  ~/Documents/github/buildtest/ [buildtest_info] buildtest info    
╭────────────────────────────────────────────── buildtest details ───────────────────────────────────────────────╮                                                                                                                         
│                                                                                                                │                                                                                                                         
│ Buildtest Version:        0.15.0                                                                               │                                                                                                                         
│ Buildtest Path:           /Users/siddiq90/Documents/github/buildtest/bin/buildtest                             │                                                                                                                         
│ Configuration File:       /Users/siddiq90/Documents/github/buildtest/buildtest/settings/config.yml             │                                                                                                                         
│ Available Systems:        ['generic']                                                                          │                                                                                                                         
│ Active System:            generic                                                                              │                                                                                                                         
│ Available Executors:      ['generic.local.bash', 'generic.local.sh', 'generic.local.csh', 'generic.local.zsh'] │                                                                                                                         
│ Build History Directory:  /Users/siddiq90/Documents/github/buildtest/var/.history                              │                                                                                                                         
│ Number of builds:         1                                                                                    │                                                                                                                         
│ Buildspec Cache File:     /Users/siddiq90/Documents/github/buildtest/var/buildspecs/cache.json                 │                                                                                                                         
│ Default Report File:      /Users/siddiq90/Documents/github/buildtest/var/report.json                           │                                                                                                                         
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯                                                                                                                         
╭─────────────────────────────────────── system details ───────────────────────────────────────╮                                                                                                                                           
│                                                                                              │                                                                                                                                           
│ Python Path:         /Users/siddiq90/.local/share/virtualenvs/buildtest-Ir4AdrfC/bin/python3 │                                                                                                                                           
│ Python Version:      3.7.3                                                                   │                                                                                                                                           
│ Processor:           i386                                                                    │                                                                                                                                           
│ Host:                DOE-7086392                                                             │                                                                                                                                           
│ Machine:             x86_64                                                                  │                                                                                                                                           
│ Operating System:    darwin                                                                  │                                                                                                                                           
│ Module System:       lmod                                                                    │                                                                                                                                           
│                                                                                              │                                                                                                                                           
╰──────────────────────────────────────────────────────────────────────────────────────────────╯                                                                                                                                           
black: /Users/siddiq90/.local/share/virtualenvs/buildtest-Ir4AdrfC/bin/black
black version: black, 22.6.0 (compiled: yes)
Python (CPython) 3.7.3

pyflakes: /Users/siddiq90/.local/share/virtualenvs/buildtest-Ir4AdrfC/bin/pyflakes
pyflakes version: 2.4.0 Python 3.7.3 on Darwin

isort: /Users/siddiq90/.local/share/virtualenvs/buildtest-Ir4AdrfC/bin/isort
                 _                 _

                 (_) ___  ___  _ __| |_
                 | |/ _/ / _ \/ '__  _/
                 | |\__ \/\_\/| |  | |_
                 |_|\___/\___/\_/   \_/
       isort your imports, so you don't have to.
                     VERSION 5.10.1


```

The output is colored 

Screen Shot 2022-07-06 at 4 21 59 PM

### CODE REVIEW

**Comment by Xiangs18** [comment]
Hi @shahzebsiddiqui, LGTM. An overview provided by **buildtest info** is nice.

**Review by Xiangs18 — APPROVED** [review]

**Comment by shahzebsiddiqui** [comment]
@JeffreyFG and @prathmesh4321 do you have any feedback pertaining to this command before we merge this. Please review and comment.

**Review by prathmesh4321 — APPROVED** [review]
@shahzebsiddiqui This looks good to me.

**Comment by shahzebsiddiqui** [comment]
thanks for your feedback @prathmesh4321 @Xiangs18 ill merge this in

**Pull request merged**
