### PR TITLE
Update Regression Test Docs

### PR DESCRIPTION
**Pull request by shahzebsiddiqui**
This PR does the following
- Update the Regression Testing Docs to address #218 and how user can get started
- Remove unused imports throughout project thanks to PyCharm
- Minor tweak to conf.py

### CODE REVIEW

**Comment by vsoch** [comment]
@shahzebsiddiqui I can review this when the failed tests in the CI above are addressed.

**Comment by shahzebsiddiqui** [comment]
> @shahzebsiddiqui I can review this when the failed tests in the CI above are addressed.

I dont think there is an issue with CI tests according to Build 294 https://travis-ci.com/github/HPC-buildtest/buildtest-framework/builds/153843814 all Travis tests passed. 
Coveralls is failing but doesn't show anything outstanding why its failing other than decrease on coverage report which is insignificant. 

Codefactor is not important, i probably should remove this autocheck. It was handy but now i rarely look at it.

**Comment by vsoch** [comment]
okay I'm good with merge, but could we please remove tests that are no longer considered important? It feels like noise at this point.

**Review by vsoch — APPROVED** [review]

**Comment by shahzebsiddiqui** [comment]
> okay I'm good with merge, but could we please remove tests that are no longer considered important? It feels like noise at this point.

I agree, i will remove some of the regtest that are not needed. It will lower coverage but it's ok. Some of these are overhead and maybe its the feature that needs to be removed. I will look through the tests and see what can be removed.

**Pull request merged**
