### PR TITLE
update org and repo  name 

### PR DESCRIPTION
**Pull request by shahzebsiddiqui**
@vsoch so i have tried to update most of the integrations to the new name. I have had some issues with renaming org for CodeFactor and Snyk. I got coveralls, Travis, codecov working.

The codefactor is named to "buildntest" and i can't seem to change it. I invited you as admin i was wondering to see if there is any way to fix it. 

For snyk i tried some way to update org and it didn't let me. Now its bit weird it's url is set to my name which is odd. Any way to fix this? 
https://www.codefactor.io/repository/github/buildntest/buildtest
https://app.snyk.io/org/shahzebsiddiqui-github-marketplace/project/58109ea9-230e-4c78-a412-c577b5d24f75/

The link for snyk should go to https://app.snyk.io/org/buildtesters/ but it is not. I figured it may be we need to remove the github integration and try to add it again but didn't seem to get any luck.

### CODE REVIEW

**Comment by vsoch** [comment]
You need to update the whitelist for the urlchecker with the new repo name, these settings urls should be skipped.
0A3091E3-FDFE-43E0-9A48-16A15FB16662

**Review by vsoch — CHANGES_REQUESTED** [review]
Settings url needs whitelisting.

**Comment by vsoch** [comment]
@shahzebsiddiqui tests should pass before requesting review. I think you could have looked and deduced this error.

**Comment by shahzebsiddiqui** [comment]
> @shahzebsiddiqui tests should pass before requesting review. I think you could have looked and deduced this error.

Yep I tested this locally and saw this broken link which was reported falsely. I will update the white list and fix this shortly.

**Comment by shahzebsiddiqui** [comment]
We you able to get admin access CodeFactor i believe i sent you invite, I am having trouble with Snyk, even though urlchecker reported these are passing the links are not right and i'd like to fix them some how.

**Review by vsoch — APPROVED** [review]

**Pull request merged**
