### PR TITLE
Add code coverage for multiple compilers with script schema

### LINKED ISSUE #1444: Add code coverage for method _process_compiler_config
The codecov report for https://app.codecov.io/gh/buildtesters/buildtest/blob/devel/buildtest/builders/base.py indicates we have no coverage over this method. See below. Let's add coverage for this
Screen Shot 2023-04-18 at 3 50 50 PM

### PR DESCRIPTION
**Pull request by Mariamajib**
1. Created a symlink "stream_example.yml" to test the method process_compiler_config  https://buildtest.readthedocs.io/en/devel/buildspecs/compiler.html#running-stream-benchmark-with-multiple-compilers
2. Added  method_process_compiler_config https://github.com/buildtesters/buildtest/blob/devel/tests/builders/test_builders.py
3. Created a relative path to stream_examples.yml symlink

### CODE REVIEW

**Comment by braeeast2001** [comment]
1. @Mariamajib Please assign this PR to yourself
2. Please retitle this PR to be a message about the general objective

**Comment by Mendi03** [comment]
@Mariamajib Make sure to link your issue to this pull request.

**Comment by braeeast2001** [comment]
1. Please retitle your pull request to point towards the overall objective of your issue.
2. @Mariamajib Please assign this to yourself

**Comment by shahzebsiddiqui** [comment]
@Mariamajib please remove the `.swp` file

**Review by shahzebsiddiqui — CHANGES_REQUESTED** [review]
can you please check the style check the yamllint check is failing. This package should be available if you did `pip install -r docs/requirements.txt`. If its set then just simply run `yamllint buildtest tests` at the root of directory and fix all the error messages. Ignore the warning. For more details see https://yamllint.readthedocs.io/en/stable/

**Comment by Mendi03** [comment]
The tests all ran to completion; however, something I noticed is that coverage was not added to the file specified in the original issue. Instead, Coverage was added to 3 different files as seen [here](https://app.codecov.io/gh/buildtesters/buildtest/pull/1515?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=checks&utm_campaign=pr+comments&utm_term=buildtesters)

@shahzebsiddiqui What would be the next steps?

**Comment by Mariamajib** [comment]
I discovered that the coverage was added to the file specified in the original issue base.py but it was under the indirect changes @shahzebsiddiqui @Mendi03 . Here is the link https://app.codecov.io/gh/buildtesters/buildtest/pull/1515/blob/buildtest/builders/base.py

**Comment by Mendi03** [comment]
> I discovered that the coverage was added to the file specified in the original issue base.py but it was under the indirect changes @shahzebsiddiqui @Mendi03 . Here is the link https://app.codecov.io/gh/buildtesters/buildtest/pull/1515/blob/buildtest/builders/base.py

You're right! Let's wait and see what @shahzebsiddiqui has to say

**Review by shahzebsiddiqui — APPROVED** [review]
@Mariamajib this looks good. Regression test is passing and i see code coverage is showing up.

Thanks and great work!. Congrats on your 1st contribution

**Pull request merged**
