### PR TITLE
Added --filterfields & --formatfields option

### LINKED ISSUE #1224: [FEATURE]: list filter and format fields for 'buildtest report'
### Please describe your feature request

similar to #1221 we should have an option to list filter and format fields for **buildtest report** that will show the fields. We need two options ``buildtest report --filterfields`` and ``buildtest report --formatfields`` that will display the filter and format fields which is the first column of the output under **Field**.

This should be displayed as raw text that can be useful for tab completion

```
(buildtest)  ~/Documents/github/buildtest/docs/ [devel] buildtest rt --helpfilter                 
                       Filter Fields                        
┏━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┓
┃ Field      ┃ Description                ┃ Expected Value ┃
┡━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━┩
│ buildspec  │ Filter by buildspec file   │ FILE           │
│ name       │ Filter by test name        │ STRING         │
│ executor   │ Filter by executor name    │ STRING         │
│ returncode │ Filter tests by returncode │ INT            │
│ state      │ Filter by test state       │ PASS/FAIL      │
│ tags       │ Filter tests by tag name   │ STRING         │
└────────────┴────────────────────────────┴────────────────┘
(buildtest)  ~/Documents/github/buildtest/docs/ [devel] buildtest rt --helpformat
                                  Format Fields                                  
┏━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Field      ┃ Description                                                      ┃
┡━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ buildspec  │ Buildspec File                                                   │
│ buildenv   │ Show build environment file for test                             │
│ command    │ Command executed                                                 │
│ compiler   │ Retrieve compiler used for test (applicable for compiler schema) │
│ endtime    │ End Time for test                                                │
│ errfile    │ Error File                                                       │
│ executor   │ Name of executor used for running test                           │
│ hostname   │ Hostname of machine where job was submitted from                 │
│ full_id    │ Fully qualified build identifier                                 │
│ id         │ Unique build identifier                                          │
│ metrics    │ List all metrics for test                                        │
│ name       │ Name of test                                                     │
│ outfile    │ Output file                                                      │
│ returncode │ Return Code                                                      │
│ runtime    │ Total runtime in seconds                                         │
│ schemafile │ Schema file used for validating test                             │
│ starttime  │ Start time of test                                               │
│ state      │ State of test (PASS/FAIL)                                        │
│ tags       │ Tag name                                                         │
│ testroot   │ Root of test directory                                           │
│ testpath   │ Path to test                                                     │
│ user       │ User who ran the test                                            │
└────────────┴──────────────────────────────────────────────────────────────────┘

```

### Post question in Slack

- [X] I agree that I posted my question in [slack](https://hpcbuildtest.slack.com/) before creating this issue

### Is there an existing issue

- [X] I confirm there is no existing [issue](https://github.com/buildtesters/buildtest/issues) for this issue

### PR DESCRIPTION
**Pull request by prathmesh4321**
buildtest report --filterfields & buildtest report --formatfields

image

### CODE REVIEW

**Comment by prathmesh4321** [comment]
@shahzebsiddiqui Could you please check if the test at line 67 is added by mistake in the codebase as the test is already written in test_report_format() function?
https://github.com/buildtesters/buildtest/blob/issue_1224/tests/cli/test_report.py#:~:text=.print_raw_filter_fields()-,%23%20run%20%27buildtest%20report%20%2D%2Dhelpfilter%27,report.print_format_fields(),-report%20%3D%20Report

**Comment by shahzebsiddiqui** [comment]
> @shahzebsiddiqui Could you please check if the test at line 67 is added by mistake in the codebase as the test is already written in test_report_format() function? https://github.com/buildtesters/buildtest/blob/issue_1224/tests/cli/test_report.py#:~:text=.print_raw_filter_fields()-,%23%20run%20%27buildtest%20report%20%2D%2Dhelpfilter%27,report.print_format_fields(),-report%20%3D%20Report

That method you are referring to is for testing the `buildtest rt --helpfilter` and `buildtest rt --helpformat` which will print this in table.

**Review by shahzebsiddiqui — CHANGES_REQUESTED** [review]
The implementation looks good. Next step is to 

1. Add documentation
2. Update output in `buildtest help`

**Comment by prathmesh4321** [comment]
> The implementation looks good. Next step is to
> 
> 1. Add documentation
> 2. Update output in `buildtest help`

I have added the documentation please let me know if anything else needs to be added @shahzebsiddiqui

**Review by shahzebsiddiqui — APPROVED** [review]
thanks @prathmesh4321 this looks good.

**Pull request merged**
