### PR TITLE
Adding zenodo.json to devel

### PR DESCRIPTION
**Pull request by vsoch**
This will add a zenodo.json to the development branch. @shahzebsiddiqui I left your affiliation off (which is valid to do, you technically don't need to add this or the orcid id!).

Signed-off-by: vsoch <vsochat@stanford.edu>

### CODE REVIEW

**Comment by vsoch** [comment]
heads up that https://codecov.io/gh/HPC-buildtest/buildtest-framework (I think this was recently added?) is timing out, so it's going to fail the urlchecker.

**Comment by shahzebsiddiqui** [comment]
@vsoch so if i understand zenodo needs to have access to the repo in order for this to work. Looking at https://guides.github.com/activities/citable-code/ 

If i understand, a new release from buildtest will get updated in https://zenodo.org/

**Comment by vsoch** [comment]
Yes, in the past it used to be that you manually connected (and then future releases would trigger an update) but it looks like they have a GitHub integration now (that you just added?) datalad is a good project to look at as an example because they've been using it for quite some time.

**Comment by vsoch** [comment]
okay ready for review! You can test the redirect page by clicking https://500-120906408-gh.circle-artifacts.com/0/usrse.github.io/2020-april-workshop/index.html. It should wait 2 seconds then redirect you - if the user has any issue there is also a link. It's done by way of the meta tag, and can be added to  any page with `redirect: <url>` in the front end matter. I also added documentation to the README so this is known in the future.

**Comment by vsoch** [comment]
oops sorry posted in wrong pr! lol

**Review by shahzebsiddiqui — APPROVED** [review]

**Comment by shahzebsiddiqui** [comment]
Thanks @vsoch let's see how this works out. I believe i have access to the paper when i login to Springer and there is a shared link to access the actual paper. I think it may only be accessible to me since i am the author, but i am not sure if other's want to see paper if they have to pay to access it 

The paper is now outdated given the recent changes, which warrants for a new paper let's see. For now i am trying to keep all the references under https://buildtest.readthedocs.io/en/devel/references.html

**Comment by vsoch** [comment]
Sounds good, we can add a badge to the README when it's merged and devel released. Feel free to update the citations section with a Zenodo DOI (it's considered a separate DOI for the software, separate from that first paper).

**Comment by shahzebsiddiqui** [comment]
> Sounds good, we can add a badge to the README when it's merged and devel released. Feel free to update the citations section with a Zenodo DOI (it's considered a separate DOI for the software, separate from that first paper).

I am not sure what or how to update citation section, it's bit new trying to get up to speed on this.

**Pull request merged**
