### PR TITLE
Update settings schema field $id and title

### PR DESCRIPTION
**Pull request by shahzebsiddiqui**
This PR must be merged after merging https://github.com/HPC-buildtest/schemas/pull/26

### CODE REVIEW

**Comment by vsoch** [comment]
An unrelated question while we are waiting on the other PR - any thought / updates about the name for the organization? I think this should be decided before some newer release in the next few months.

**Review by vsoch — APPROVED** [review]

**Comment by shahzebsiddiqui** [comment]
> An unrelated question while we are waiting on the other PR - any thought / updates about the name for the organization? I think this should be decided before some newer release in the next few months.

I was hoping to get namespace **buildtest** https://github.com/buildtest but there has been no response from the group, emailed all three of the folks. 

Unrelated to the org, i was thinking about name for the ``schema``  repo could we name it **buildtest-api** or **buildspec-api** or **api**. Since the test are called Buildspec, i figured it would make sense to name it either **Buildspec-API**  but it contains schema for buildtest as well.

**Comment by vsoch** [comment]
I think it contains schemas, so we should call it schemas :) It's under the buildtest (err what should be buildtest) org so the association is implied.

**Comment by vsoch** [comment]
To give feedback on "buildspec-api" - an api refers to an "application programming interface" which usually comes down to a server that is _serving endpoints that might deliver json_. This is an entirely different concept than a schema, which might be the rules for defining how that json is structured. It would be very misleading to call a repo of schemas an api.

**Comment by shahzebsiddiqui** [comment]
fair enough, according to Github they can't do much i asked them twice and this was their response. We can't wait indefinitely i dont think these three users will ever reply if it's a miracle. We don't have a trademark so Github can't help. 

Even **buildtests** is taken https://github.com/buildtests 👎 

image

**buildtesters** is available. Unfortunately namespace are not case sensitive otherwise we could have done **Buildtest** but that is not possible either.

**Comment by vsoch** [comment]
Any other ideas?

**Comment by vsoch** [comment]
What about `building` ?

**Comment by shahzebsiddiqui** [comment]
So org name doesn't have to imply change to command ``buildtest`` or should it? 
What about ``buildtester`` or ``buildertest`` I am kinda bad at names. I liked the name ``buildtest`` since it's meant to automate building of tests and is very generic. Since it's meant for HPC at that time i couldn't think of anything so i named org ``HPC-buildtest``. But now this also supports HPC Software and System Testing so maybe the org name could be anything. Generally i see the org name is name of the opensource tool but that's not always the case. I think the name should be unique, short and easily searched.  I think the name of org should also be done in sync with the logo so there is a relevant logo to the name of the org.


This may imply changes to docs, but prefer the url

**Comment by vsoch** [comment]
See issue #280 I put a lot of thought there! I like buildspec :)

**Pull request merged**
