### PR TITLE
.Several Minor fixes related to documentation warning, and examples directory

### LINKED ISSUE #223: Warning in readthedocs build
This is a snapshot of the warning during docs build. The docstring with **Parameters** with a 
heading line is something sphinx does not like. The warnings related to autodoc is not causing issue with API docs https://buildtest.readthedocs.io/en/devel/py-modindex.html but it would be nice to get rid of these warnings.

Some of the output is not formatted properly in the API docs. This kinda relates to getting a standard for docstring #220 

```
/home/docs/checkouts/readthedocs.org/user_builds/buildtest/checkouts/devel/buildtest/buildsystem/base.py:docstring of buildtest.buildsystem.base.BuildConfig.load:5: WARNING: Unexpected section title.

Parameters
==========
/home/docs/checkouts/readthedocs.org/user_builds/buildtest/checkouts/devel/buildtest/buildsystem/base.py:docstring of buildtest.buildsystem.base.BuilderBase.get_formatted_time:5: WARNING: Unexpected section title.

Parameters
==========
/home/docs/checkouts/readthedocs.org/user_builds/buildtest/checkouts/devel/buildtest/buildsystem/schemas/utils.py:docstring of buildtest.buildsystem.schemas.utils.get_latest:4: WARNING: Unexpected section title.

Parameters
==========
/home/docs/checkouts/readthedocs.org/user_builds/buildtest/checkouts/devel/buildtest/buildsystem/schemas/utils.py:docstring of buildtest.buildsystem.schemas.utils.get_schema_fullpath:4: WARNING: Unexpected section title.

Parameters
==========
/home/docs/checkouts/readthedocs.org/user_builds/buildtest/checkouts/devel/buildtest/buildsystem/schemas/utils.py:docstring of buildtest.buildsystem.schemas.utils.get_schema_version:5: WARNING: Unexpected section title.

Parameters
==========
/home/docs/checkouts/readthedocs.org/user_builds/buildtest/checkouts/devel/buildtest/buildsystem/schemas/utils.py:docstring of buildtest.buildsystem.schemas.utils.load_recipe:4: WARNING: Unexpected section title.

Parameters
==========
/home/docs/checkouts/readthedocs.org/user_builds/buildtest/checkouts/devel/buildtest/buildsystem/schemas/utils.py:docstring of buildtest.buildsystem.schemas.utils.load_schema:4: WARNING: Unexpected section title.

Parameters
==========
/home/docs/checkouts/readthedocs.org/user_builds/buildtest/checkouts/devel/buildtest/system.py:docstring of buildtest.system.BuildTestSystem.check_scheduler:3: WARNING: Unexpected indentation.
/home/docs/checkouts/readthedocs.org/user_builds/buildtest/checkouts/devel/docs/api/buildtest.tools.rst:15: WARNING: toctree contains reference to nonexisting document 'api/buildtest.tools.writer'
WARNING: autodoc: failed to import module 'tools' from module 'buildtest'; the following exception was raised:
No module named 'buildtest.tools'
WARNING: autodoc: failed to import module 'tools.build' from module 'buildtest'; the following exception was raised:
No module named 'buildtest.tools'
WARNING: autodoc: failed to import module 'tools.buildsystem' from module 'buildtest'; the following exception was raised:
No module named 'buildtest.tools'
WARNING: autodoc: failed to import module 'tools.buildsystem.dry' from module 'buildtest'; the following exception was raised:
No module named 'buildtest.tools'
WARNING: autodoc: failed to import module 'tools.buildsystem.singlesource' from module 'buildtest'; the following exception was raised:
No module named 'buildtest.tools'
WARNING: autodoc: failed to import module 'tools.buildsystem.status' from module 'buildtest'; the following exception was raised:
No module named 'buildtest.tools'
WARNING: autodoc: failed to import module 'tools.config' from module 'buildtest'; the following exception was raised:
No module named 'buildtest.tools'
WARNING: autodoc: failed to import module 'tools.configuration' from module 'buildtest'; the following exception was raised:
No module named 'buildtest.tools'
WARNING: autodoc: failed to import module 'tools.configuration.config' from module 'buildtest'; the following exception was raised:
No module named 'buildtest.tools'
WARNING: autodoc: failed to import module 'tools.defaults' from module 'buildtest'; the following exception was raised:
No module named 'buildtest.tools'
WARNING: autodoc: failed to import module 'tools.file' from module 'buildtest'; the following exception was raised:
No module named 'buildtest.tools'
WARNING: autodoc: failed to import module 'tools.get' from module 'buildtest'; the following exception was raised:
No module named 'buildtest.tools'
WARNING: autodoc: failed to import module 'tools.log' from module 'buildtest'; the following exception was raised:
No module named 'buildtest.tools'
WARNING: autodoc: failed to import module 'tools.menu' from module 'buildtest'; the following exception was raised:
No module named 'buildtest.tools'
WARNING: autodoc: failed to import module 'tools.show' from module 'buildtest'; the following exception was raised:
No module named 'buildtest.tools'
WARNING: autodoc: failed to import module 'tools.system' from module 'buildtest'; the following exception was raised:
No module named 'buildtest.tools'
looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/docs/checkouts/readthedocs.org/user_builds/buildtest/checkouts/devel/docs/api/buildtest.rst: WARNING: document isn't included in any toctree
/home/docs/checkouts/readthedocs.org/user_builds/buildtest/checkouts/devel/docs/api/buildtest.tools.rst: WARNING: document isn't included in any toctree
done
```

### PR DESCRIPTION
**Pull request by shahzebsiddiqui**
This PR fix #223 related to documentation warning
We also add pytest, and black in requirements.txt  so its automatically
installed when setting up their python environment.
The docstring had a header section next to Parameters that needed to be
removed since sphinx reported that as a warning
Adding examples directory to store some example test configuration
for script schema. It makes sense to store them in buildtest-framework
to serve out the Getting Started Guide for buildtest docs.

### CODE REVIEW

**Comment by shahzebsiddiqui** [comment]
@vsoch 
This PR addresses several warnings in documentation build in #223. I am building this locally for now, the autodoc warning is not showing up. Not sure if it was a corrupt environment on my end, but it is working now.

```
(docs) login2.stampede2(1133)$ cd docs/
(docs) login2.stampede2(1134)$ make clean
Removing everything under '_build'...
(docs) login2.stampede2(1135)$ make html
Running Sphinx v2.4.3
Creating file api/buildtest.rst.
Creating file api/buildtest.config.rst.
Creating file api/buildtest.defaults.rst.
Creating file api/buildtest.exceptions.rst.
Creating file api/buildtest.log.rst.
Creating file api/buildtest.main.rst.
Creating file api/buildtest.system.rst.
Creating file api/buildtest.buildsystem.rst.
Creating file api/buildtest.buildsystem.base.rst.
Creating file api/buildtest.buildsystem.schemas.rst.
Creating file api/buildtest.buildsystem.schemas.utils.rst.
Creating file api/buildtest.docgen.rst.
Creating file api/buildtest.docgen.main.rst.
Creating file api/buildtest.menu.rst.
Creating file api/buildtest.menu.build.rst.
Creating file api/buildtest.menu.config.rst.
Creating file api/buildtest.menu.get.rst.
Creating file api/buildtest.menu.show.rst.
Creating file api/buildtest.menu.status.rst.
Creating file api/buildtest.utils.rst.
Creating file api/buildtest.utils.command.rst.
Creating file api/buildtest.utils.file.rst.
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 36 source files that are out of date
updating environment: [new config] 36 added, 0 changed, 0 removed
reading sources... [100%] what_is_buildtest
/work/06908/sms1990/stampede2/buildtest-framework/docs/references.rst:2: WARNING: Duplicate explicit target name: "pdf".
/work/06908/sms1990/stampede2/buildtest-framework/docs/references.rst:2: WARNING: Duplicate explicit target name: "pptx".
/work/06908/sms1990/stampede2/buildtest-framework/docs/references.rst:2: WARNING: Duplicate explicit target name: "video".
/work/06908/sms1990/stampede2/buildtest-framework/docs/references.rst:2: WARNING: Duplicate explicit target name: "pdf".
/work/06908/sms1990/stampede2/buildtest-framework/docs/references.rst:2: WARNING: Duplicate explicit target name: "pptx".
/work/06908/sms1990/stampede2/buildtest-framework/docs/references.rst:2: WARNING: Duplicate explicit target name: "pdf".
/work/06908/sms1990/stampede2/buildtest-framework/docs/references.rst:2: WARNING: Duplicate explicit target name: "pdf".
looking for now-outdated files... none found
pickling environment... done
checking consistency... /work/06908/sms1990/stampede2/buildtest-framework/docs/api/buildtest.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] what_is_buildtest
generating indices...  genindex py-modindexdone
writing additional pages...  search/home1/06908/sms1990/.local/share/virtualenvs/docs-qbK3SfF3/lib/python3.7/site-packages/sphinx_rtd_theme/search.html:21: RemovedInSphinx30Warning: To modify script_files in the theme is deprecated. Please insert a <script> tag directly in your theme instead.
  {% endblock %}
done
copying images... [100%] contributing/buildtest_merge_options.png
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 8 warnings.

The HTML pages are in _build/html.

```

**Comment by vsoch** [comment]
@shahzebsiddiqui it seems we are waiting on guardrails/scan, I'm not actually able to see what this is doing without giving Oauth permission. Is this a necessary integration?

**Comment by shahzebsiddiqui** [comment]
There seems to be some issue logged in now and took a screenshot. I can remove this integration. It was for security, seems like we can still use Snyk which does is for security vulnerability. I like the bot pr to fix issues. Guardrails doesnt do that but just gives you a report. I have yet to use it. Makes sense to remove it

image

**Comment by shahzebsiddiqui** [comment]
I have removed Guardrails and few other apps and third party access not needed at this point. So you can ignore that check for this PR. Going forward, guardrails shouldnt be running.

**Comment by vsoch** [comment]
Ah, ok! Yes GitHub has good (and still improving) security audits, so I think we are best to remove. Generally in terms of integrations (and I've said this before) I think it's better to be conservative. Every app you connect is giving permissions to your account / repo, which should be done conservatively I think.

**Comment by vsoch** [comment]
And apologies about the `Parameters` with `======` in the docstrings - that was totally me! :)

**Review by vsoch — APPROVED** [review]

**Pull request merged**
