### PR TITLE
Remove pip packaging

### PR DESCRIPTION
**Pull request by shahzebsiddiqui**
removing the packaging files related to buildtest-framework. This caused confusion reported by @vsoch.

### CODE REVIEW

**Comment by shahzebsiddiqui** [comment]
@vsoch cleaning up my mess.

**Comment by vsoch** [comment]
Thank you! I'll start working from devel - is it all set?

**Comment by shahzebsiddiqui** [comment]
yea its fine for now.  I have some ideas on YAML schema but need to carefully work through this.
I have some ideas in covered in and this where i need to put more efforts.
https://github.com/HPC-buildtest/buildtest-framework/issues/135
https://github.com/HPC-buildtest/buildtest-framework/wiki/Yaml-Schema-Draft

Any ideas are always welcomed.

**Comment by vsoch** [comment]
Thank you @shahzebsiddiqui ! if it's okay with you, I'd like a few days to test and do some small changes, and I'll open a PR after that. Once I'm familiar with the structure and general flow of things I can give much better feedback about the specific issues that we've discussed.

**Comment by shahzebsiddiqui** [comment]
Of course, take your time, and your feedback will be great. It would certainly help to know which features are useful and which are not. That will help guide where to put more work. Also there is a devel doc branch https://buildtest.readthedocs.io/en/devel/index.html that can be used for referring to devel changes which i generally add as part of release before merging everything to master.

I try to document everything, but certainly if you come across some missing docs please open an issue.
There is a doc issue template dedicated for these issues

**Pull request merged**
