### PR TITLE
Add short option "-t" for --testpath

### PR DESCRIPTION
**Pull request by braeeast2001**
Complete the following to resolve this issue:

> - [ ] Edit [Bash Completion](https://github.com/buildtesters/buildtest/blob/devel/bash_completion.sh)
> - [x] Edit Argparse [Here](https://github.com/buildtesters/buildtest/blob/devel/buildtest/cli/__init__.py)
> - [x] Change --testpath to -t in [tools/docs.py](https://github.com/buildtesters/buildtest/blob/devel/buildtest/tools/docs.py)

### CODE REVIEW

**Comment by braeeast2001** [comment]
@shahzebsiddiqui 
The bash completion script already had "-t" for "--testpath" in the following lines: [Line 203](https://github.com/buildtesters/buildtest/blob/557167f3da8d77b96689fed2ceab04e72d3a7b2a/bash_completion.sh#L203C9-L203C9) and [Line 303](https://github.com/buildtesters/buildtest/blob/557167f3da8d77b96689fed2ceab04e72d3a7b2a/bash_completion.sh#L303)

I believe these are the only two places where the short option needed to be, please let me know if I missed something.

**Review by shahzebsiddiqui — COMMENTED** [review]
good job @braeeast2001 you are on the right track. Please complete the bash completion script and also try to find any references to `--testpath` in docs where you see `.. command-output` and you can change that back to `-t` as the short option.

**Comment by shahzebsiddiqui** [comment]
@braeeast2001 can you take a look at the docs check see https://readthedocs.org/api/v2/build/21489119.txt its failing

```
"/home/docs/.asdf/installs/python/3.8.17/lib/python3.8/argparse.py", line 1548, in _handle_conflict_error\n    raise ArgumentError(action, message % conflict_string)\nargparse.ArgumentError: argument -t/--testpath: conflicting option string: -t')
```

There seems to be a conflicting short option `-t`. Perhaps this is still coming from the `-t/--theme` option can you please check. Try building the docs locally that might help solve the problem

**Comment by shahzebsiddiqui** [comment]
i am closing this PR @braeeast2001 since you have not worked on it recently. I will complete this task.

Thanks

**Pull request closed without merging**
