### PR TITLE
reorg regtests based on source file to be tested 

### LINKED ISSUE #216: Define a standard directory structure for Regression Tests
Currently, there is no standard in place for writing regression tests. At the moment, the regtest in https://github.com/HPC-buildtest/buildtest-framework/tree/master/tests are mostly unit test. I propose the directory structure for unit tests map to the file name in the following way.

To test for source file ``buildtest/exceptions.py`` there should be a test ``tests/test_exceptions.py``. This makes it easy to associate the regression test with each source file and allows new users to easy contribute back and troubleshoot regression test.

Each sub-directory in ``buildtest`` can be mapped to ``tests`` so a file ``buildtest/utils/file.py`` should have a test ``tests/utils/test_file.py``. We should also document some best practice on how to start writing regression tests and contribute back. It should be this page https://buildtest.readthedocs.io/en/devel/contributing/regression_testing.html. It may not be clear to folks new to pytest that all tests start with ``test_<name>.py`` we should document this.

It may be worth mentioning if we decide on a standard for testing classes. Right now if there is a class ``BuildTestCommand`` there is a class ``TestBuildTestCommand`` which will test the class. So name of class is ``Test<className>``. 

For all methods, there is no standard naming scheme yet, but a simple scheme could be simple as ``test_<method-name>``. This may not work for all cases since some methods may need multiple tests so having meaningful names would be required.

### PR DESCRIPTION
**Pull request by shahzebsiddiqui**
This PR is mapping all the unit tests to the source file to be tested. The structure of the tests looks as follows

```
(docs) ssi29@ag-mxg-hulk090> tree -P test_*.py tests/
tests/
├── menu
│   └── test_config.py
├── test_defaults.py
├── test_exceptions.py
└── utils
    ├── test_command.py
    └── test_file.py

2 directories, 5 files
```

### CODE REVIEW

**Comment by shahzebsiddiqui** [comment]
@vsoch  i need to rebase this PR so first check #217 once its merged i will rebase this with ``devel``.

**Review by vsoch — CHANGES_REQUESTED** [review]
If this has #217 as a dependency, for the reasons I listed there, we must wait. I am in huge support of renaming the tests for this structure!

**Comment by shahzebsiddiqui** [comment]
> @vsoch i need to rebase this PR so first check #217 once its merged i will rebase this with `devel`.

Sounds good  with me

**Comment by vsoch** [comment]
@shahzebsiddiqui this should be unblocked in that you can rebase with devel and then I can review.

**Comment by shahzebsiddiqui** [comment]
@vsoch i made a silly mistake hopefully this https://github.com/HPC-buildtest/buildtest-framework/pull/218/commits/c3eb63b2a830e3f716ece64c7fc33baf57b4ced3 will resolve the failure. I forgot to delete the test since it was declared in ``test_show.py``. Once all tests are green in Travis it should make more sense. 

Anyhow the directory structure is the following 

```
(docs) ssi29@ag-mxg-hulk090> tree tests/
tests/
├── buildsystem
│   ├── __init__.py
│   └── test_base.py
├── __init__.py
├── install_deps.sh
├── menu
│   ├── __init__.py
│   ├── test_config.py
│   └── test_show.py
├── run_tests.sh
├── test_defaults.py
├── testdir
│   └── slurm-hello.yml
├── test_exceptions.py
└── utils
    ├── __init__.py
    ├── test_command.py
    └── test_file.py

4 directories, 14 files

```

Every test belongs to a file mapping in ``buildtest``. Since these are unit tests mostly, we add tests in the appropriate file so its easier for other contributors to add files in right location and to troubleshoot tests much easier. So if a test ``tests/utils/test_command.py`` is failing that means there is an issue with one of the tests that belongs to ``buildtest/utils/command.py``. Hope that makes sense.

**Review by vsoch — APPROVED** [review]
LGTM

**Comment by vsoch** [comment]
It’s beautifully done! Let’s merge this.

**Pull request merged**
